sudo: false
language: python
services:
  - redis
python:
  - "3.6"
install:
  - pip install -e .
  - pip install pytest pytest-cov coveralls pytest-mock flake8 flake8-isort
script:
  - flake8 .
  - RUN_SLOW_TESTS_TOO=1 py.test --cov rq --durations=5
after_success:
  - coveralls
